apiVersion: tenancy.kcp.io/v1alpha1
kind: WorkspaceType
metadata:
  name: widgets
spec:
  extend:
    with:
    - name: universal
      path: root
  defaultAPIBindings:
  - path: root:widgets
    export: data.my.domain
